SELECT DISTINCT ?item ?itemLabel ?itemDescription ?nga WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
  ?item p:P4683 ?artid.
  ?item wdt:P4683 ?nga
}
LIMIT 50000 OFFSET %s
